deployment:
  tasks:
    - export DEPLOYPATH=/home/kojiesanadmin/public_html/sto-online-test.bevi.ph
    - rsync -av --delete
      --exclude='.git'
      --exclude='.cpanel.yml'
      --exclude='.env'
      --exclude='node_modules'
      --exclude='storage/logs'
      --exclude='storage/framework/cache'
      --exclude='storage/framework/sessions'
      --exclude='storage/framework/views'
      --exclude='bootstrap/cache'
      --exclude='tests'
      ./ $DEPLOYPATH
    - /usr/local/bin/php $DEPLOYPATH/artisan config:cache
    - /usr/local/bin/php $DEPLOYPATH/artisan route:cache
    - /usr/local/bin/php $DEPLOYPATH/artisan view:cache
